spring.application.name=demo
# DataSource MySql

spring.profiles.active=local

# JPA/Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Thymeleaf

spring.thymeleaf.cache=false